name: gerrit-operator
namespace: "skostenko-test"
platform: "kubernetes"
image:
  name: epamedp/gerrit-operator
  version: v2.4.0

gerrit:
  deploy: true
  name: "gerrit"
  image: "openfrontier/gerrit"
  sshPort: "30001"
  port: "8080"
  volumeCapacity: 10Gi
  storageClass: gp2
  version: "3.1.4"
  admins:
    - "stub_user_one@example.com"

gitServer:
  name: "gerrit"
  user: "jenkins"
  httpsPort: 443
  nameSshKeySecret: "gerrit-ciuser-sshkey"
  sshPort: 22

edp:
  dnsWildCard: ""
  admins: