{{ if eq .Values.platform "kubernetes" }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
    name: {{ .Values.gerrit.name }}
    labels:
        app: {{ .Values.gerrit.name }}
spec:
    rules:
        - host: {{if .Values.{{ .Values.gerrit.name }}.basePath}}{{ .Values.edp.dnsWildCard }}{{else}}{{ .Values.gerrit.name }}-{{ .Values.namespace }}.{{ .Values.edp.dnsWildCard }}{{end}}
          http:
              paths:
                  - path: {{if .Values.{{ .Values.gerrit.name }}.basePath}}/{{.Values.{{ .Values.gerrit.name }}.basePath}}(/|$)(.*){{else}}/{{end}}
                    backend:
                        serviceName: {{ .Values.gerrit.name }}
                        servicePort: 8080
status:
    loadBalancer:
        ingress:
{{ end }}