{{ if eq .Values.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    labels:
        app: {{ .Values.gerrit.name }}
    name: {{ .Values.gerrit.name }}
spec:
    host: {{if .Values.gerrit.basePath}}{{ .Values.edp.dnsWildCard }}{{else}}{{ .Values.gerrit.name }}-{{ .Values.namespace }}.{{ .Values.edp.dnsWildCard }}{{end}}
    path: {{if .Values.gerrit.basePath}}/{{.Values.gerrit.basePath}}(/|$)(.*){{else}}/{{end}}
    port:
        targetPort: 8080
    tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
    to:
        kind: Service
        name: {{ .Values.gerrit.name }}
        weight: 100
    wildcardPolicy: None
status:
    ingress: []
{{ end }}